//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoBuf.Wcf.Sample.LongRunningService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LongRunningService.ILongRunning")]
    public interface ILongRunning {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongRunning/DoWork", ReplyAction="http://tempuri.org/ILongRunning/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILongRunning/DoWork", ReplyAction="http://tempuri.org/ILongRunning/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILongRunningChannel : ProtoBuf.Wcf.Sample.LongRunningService.ILongRunning, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LongRunningClient : System.ServiceModel.ClientBase<ProtoBuf.Wcf.Sample.LongRunningService.ILongRunning>, ProtoBuf.Wcf.Sample.LongRunningService.ILongRunning {
        
        public LongRunningClient() {
        }
        
        public LongRunningClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LongRunningClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LongRunningClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LongRunningClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
